[tool.poetry]
name = "magnify"
version = "0.1.6"
description = "A microscopy image processing toolkit."
authors = ["Karl Krauth <karl.krauth@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.12"
opencv-python = [
    { version = ">=4.0", markers = "sys_platform != 'darwin'" },
    { version = ">=4.0, !=4.7.0.68", markers = "sys_platform == 'darwin'" }
]
numpy = "^1.21.0"
scipy = "^1.9.0"
basicpy = "^1.0.1"
tifffile = ">=2021.11.2"
tqdm = "^4.64"
types-tqdm = "^4.64"

[tool.poetry.group.dev.dependencies]
black = ">=22.6.0"
mypy = ">=1.0.1"
pytest = ">=7.1.2"
ruff = ">=0.0.249"
sphinx = ">=5.0.2"
sphinx-press-theme = ">=0.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.mypy]
python_version = "3.10"

# Disallow untyped definitions.
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

# None and optional handling
no_implicit_optional = true

# Configuring warnings
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_redundant_casts = true

# Misc things
strict_equality = true

# Config file
warn_unused_configs = true

ignore_missing_imports = true
